### ISSUE TITLE
[Refactoring] Clothes 애니메이션 구현 / 로그인 / 회원가입  페이지 태블릿 UI 확인 / ClothesList 스크롤 구현

### ISSUE THREAD

**Issue by Hal-ang** [codestates/weSeason-client#111]
### TODO
1. [x] clothes 애니메이션 구현
2. [x] 회원가입 / 로그인 페이지 태블릿 UI 깨짐 확인
3. [x] clothesList 스크롤 구현

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Refactoring`
- Urgency: `High`

**Comment by Hal-ang** [comment]
모바일 미디어쿼리 중복 적용으로 모바일 미디어쿼리 min-width: 768 > min-width: 767 수정
