### ISSUE TITLE
[Refactoring] UI 수정

### ISSUE THREAD

**Issue by mrsimplelife** [codestates/weSeason-client#112]
### TODO
1. [x] 날씨 컴포넌트 간격조절
2. [x] 스크롤 버튼 디자인 변경
3. [x] 호버 색상 변경 
4. [x] 메뉴 디자인 변경
5. [x] 에디트 페이지 체크박스 사이즈 및 한글 적용
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Refectoring`
- Urgency: `High`
