### ISSUE TITLE
[BUG][Refectoring] 옷 1개 노출 시 ui, 모달 키워드 검색 후 클릭 시 좌표 상태 미변경, 모달 키코드 조건 수정

### ISSUE THREAD

**Issue by mrsimplelife** [codestates/weSeason-client#121]
### TODO
2. [x] 유효 아이콘 의류 1개인 경우 css 설정
3. [x] 동네 검색 모달 > 키워드 검색 후 노출 마커 클릭 시 좌표 상태 미업데이트 확인 
4. [x] 모달 ESC 키코드 인식 불가

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Refactoring`
- Urgency: `High`
