### ISSUE TITLE
[client] Main 컴포넌트 만들기

### ISSUE THREAD

**Issue by mrsimplelife** [codestates/weSeason-client#3]
### TODO
1. [x] 배경 설정
2. [x] 목업 데이터를 이용하여 weather 컴포넌트 구현
3. [x] main 페이지 ajax 호출 필요
4. [ ] clothes 컴포넌트 구현 필요

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint__NUMBER__`
- Urgency: `High`
