### ISSUE TITLE
[Client] Weather 컴포넌트 / css 디자인 재확인

### ISSUE THREAD

**Issue by Hal-ang** [codestates/weSeason-client#49]
### TODO
1. [x] 스크롤 노출, 구름 스크롤로 css 적용 고려 (css 스크롤 스타일 지정 한계로 구름 스크롤은 구현 불가, 배경등 이외 css 적용)
2. [x] 날씨 아이콘 그림자 설정
3. [x] 마이페이지, 메인, 회원탈퇴 제외 폰트 설정
5. [x] 날씨 아이콘 클릭 시 메소드 실행 구현

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Sprint3`
- Urgency: `High`
