### ISSUE TITLE
[Refactoring] 회원가입__반응형, 입력시 폼 활성화 css, 기존 컴포넌트 구조 변경

### ISSUE THREAD

**Issue by Hal-ang** [codestates/weSeason-client#75]
### TODO
1. [x] 기존 회원가입 구조 변경 (SignUp 컴포넌트 단일 처리 > UserInfo 컴포넌트 추가, userInfoForm 데이터 추가)
2. [x] 인풋 및 유저인포 타이틀 내 값 입력시 활성화
3. [x] 모든 정보 입력, 비밀번호와 비밀번화 확인의 길이가 같은 경우 가입 버튼 색상 활성화
4. [x] 상세 css 구현 

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Refactoring`
- Urgency: `High`
