### ISSUE TITLE
[Refactoring] 회원가입__create user 분기 처리, 웹 에러 모달 구현

### ISSUE THREAD

**Issue by Hal-ang** [codestates/weSeason-client#86]
### TODO
1. [x] 웹용 에러 모달 구현
2. [x] 모바일/ 태블릿용 에러 노출 구현
3. [x] ajax 호출 (가입) 구현

### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Sprint: `Refactoring`
- Urgency: `High`
